### ISSUE TITLE
Can this project  run on MacOS arm64?

### ISSUE THREAD

**Issue by arnavmeduri** [dadadadawjb/NeRFHowTo#1]
Hello, 

I am trying to run `helloworld_demo` using Python 3.11 on MacOS (arm64) and running into a couple of problems.
1.  The file `data/tiny_nerf_data.npz` does not exist in the repo, and I downloaded it from http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV20/nerf/tiny_nerf_data.npz

2. When I run train.py, I always get this error. Any idea how to get around it?
```
python train.py --config configs/helloworld_demo.txt
[1]    33459 segmentation fault  python train.py --config configs/helloworld_demo.txt
```

Appreciate any guidance! Thank you!

**Comment by arnavmeduri** [comment]
I am able to run `train.py` with Python 3.9

**Comment by dadadadawjb** [comment]
> I am able to run `train.py` with Python 3.9

Hi, 

thank you for your attention. My testing environment is also Python 3.9 but on Windows 10 arm64. The segmentation fault may be caused by `matplotlib` for Python 3.11, I guess.

**Comment by dadadadawjb** [comment]
> Hello,
> 
> I am trying to run `helloworld_demo` using Python 3.11 on MacOS (arm64) and running into a couple of problems.
> 
> 1. The file `data/tiny_nerf_data.npz` does not exist in the repo, and I downloaded it from http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV20/nerf/tiny_nerf_data.npz
> 2. When I run train.py, I always get this error. Any idea how to get around it?
> 
> ```
> python train.py --config configs/helloworld_demo.txt
> [1]    33459 segmentation fault  python train.py --config configs/helloworld_demo.txt
> ```
> 
> Appreciate any guidance! Thank you!

Yeah, the `helloworld` dataset is downloaded from this link. For other dataset types, please refer to `data/README.md`.
